/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PeriodInput = IDL.Record({
  'date' : IDL.Text,
  'summaryPrimary' : IDL.Text,
  'summarySecondary' : IDL.Text,
  'periodNumber' : IDL.Nat,
  'courseId' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const CourseRecord = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : Time,
  'year' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const PeriodRecord = IDL.Record({
  'id' : IDL.Nat,
  'date' : IDL.Text,
  'createdAt' : Time,
  'summaryPrimary' : IDL.Text,
  'summarySecondary' : IDL.Text,
  'periodNumber' : IDL.Nat,
  'courseId' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addPeriod' : IDL.Func([PeriodInput], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteCourse' : IDL.Func([IDL.Nat], [], []),
  'getAllCourses' : IDL.Func([], [IDL.Vec(CourseRecord)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCourse' : IDL.Func([IDL.Nat], [IDL.Opt(CourseRecord)], ['query']),
  'getPeriodsForDate' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Vec(PeriodRecord)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerCourse' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PeriodInput = IDL.Record({
    'date' : IDL.Text,
    'summaryPrimary' : IDL.Text,
    'summarySecondary' : IDL.Text,
    'periodNumber' : IDL.Nat,
    'courseId' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const CourseRecord = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : Time,
    'year' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const PeriodRecord = IDL.Record({
    'id' : IDL.Nat,
    'date' : IDL.Text,
    'createdAt' : Time,
    'summaryPrimary' : IDL.Text,
    'summarySecondary' : IDL.Text,
    'periodNumber' : IDL.Nat,
    'courseId' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addPeriod' : IDL.Func([PeriodInput], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteCourse' : IDL.Func([IDL.Nat], [], []),
    'getAllCourses' : IDL.Func([], [IDL.Vec(CourseRecord)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCourse' : IDL.Func([IDL.Nat], [IDL.Opt(CourseRecord)], ['query']),
    'getPeriodsForDate' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Vec(PeriodRecord)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerCourse' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };