/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CourseRecord {
  'id' : bigint,
  'name' : string,
  'createdAt' : Time,
  'year' : string,
}
export interface PeriodInput {
  'date' : string,
  'summaryPrimary' : string,
  'summarySecondary' : string,
  'periodNumber' : bigint,
  'courseId' : bigint,
}
export interface PeriodRecord {
  'id' : bigint,
  'date' : string,
  'createdAt' : Time,
  'summaryPrimary' : string,
  'summarySecondary' : string,
  'periodNumber' : bigint,
  'courseId' : bigint,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addPeriod' : ActorMethod<[PeriodInput], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteCourse' : ActorMethod<[bigint], undefined>,
  'getAllCourses' : ActorMethod<[], Array<CourseRecord>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCourse' : ActorMethod<[bigint], [] | [CourseRecord]>,
  'getPeriodsForDate' : ActorMethod<[bigint, string], Array<PeriodRecord>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerCourse' : ActorMethod<[string, string], bigint>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];